Program/Pages/Admin/CreateStaffUser.cshtml.cs
using CTTSite.Services.Interface;
using CTTSite.Services.NormalService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;
using CTTSite.Models;
using Microsoft.AspNetCore.Identity;

namespace CTTSite.Pages.Staff.Admin
{
    // Made by Christian

    [Authorize(Roles = "admin")]
    public class CreateStaffUserModel : PageModel
    {
        private IUserService _iUserService;

        [BindProperty]
        public string Email { get; set; }

        public string Password { get; set; }

        public string Message { get; set; }

        public Models.User newUser { get; set; }

        private PasswordHasher<string> _passwordHasher;

        public CreateStaffUserModel(IUserService userService)
        {
            _iUserService = userService;
            _passwordHasher = new PasswordHasher<string>();
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {           

            if (Email == null)
            {
                Message = "Please enter an email address";
                return Page();
            }

            if (!Email.Contains("@"))
            {
                Message = "Please use a valid email address!!!";
                return Page();
            }

			var chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz123456789!";
			var stringChars = new char[8];
			var random = new Random();

			for (int i = 0; i < stringChars.Length; i++)
			{
				stringChars[i] = chars[random.Next(chars.Length)];
			}

			Password = new String(stringChars);


            newUser = new Models.User(Email, _passwordHasher.HashPassword(null, Password), false, true); 
            if (_iUserService.AddUser(newUser).Result == true)
            {
                await _iUserService.AddUser(newUser);
                _iUserService.ForgottenPassword(newUser.Email, Password);

                return RedirectToPage("/Staff/UserCreatedConfirmation");
            }
            else
            {
                Message = "Email already exists!!!";
                return Page();
            }
        }
    }
}

Program/Pages/Admin/DeleteUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CTTSite.Services.Interface;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using CTTSite.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace CTTSite.Pages.Admin
{
	// Made by Christian
	[Authorize(Roles = "admin")]
	public class DeleteUserModel : PageModel
    {  
        private IUserService _iUserService;

        [BindProperty]
        public Models.User? user { get; set; }

		public DeleteUserModel(IUserService iUserService)
		{
			_iUserService = iUserService;

		}

		public IActionResult OnGet(int id)
        {
			user = _iUserService.GetUserByID(id);
			if (user == null)
				return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

			return Page();
		}

		public async Task<IActionResult> OnPostAsync()
		{
			Models.User? deletedUser = user;

			await _iUserService.DeleteUserByID(deletedUser.Id);
			
			if (deletedUser == null)
				return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

			return RedirectToPage("GetAllUsers");
		}
	}
}

Program/Pages/Admin/GetAllUsers.cshtml.cs
using CTTSite.Models;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace CTTSite.Pages.Staff.Admin
{
    // Made by Christian

    [Authorize(Roles = "admin")]
    public class GetAllUsersModel : PageModel
    {
        private IUserService _iUserService;
        public List<Models.User> _users {  get; set; }


        [BindProperty]
        public string? SearchString { get; set; }

        public GetAllUsersModel(IUserService userService)
        {
            _iUserService = userService;
            _users = _iUserService.GetAllUsers();
        }
        public void OnGet()
        {
           
        }

		public IActionResult OnGetAll()
		{
			_users = _iUserService.GetAllUsers();
			return Page();
		}

		public IActionResult OnGetSortById()
        {
            _users = _iUserService.SortById().ToList();
            return Page();
        }

        public IActionResult OnGetSortByIdDescending()
        {
            _users = _iUserService.SortByIdDescending().ToList();
            return Page();
        }

        public IActionResult OnGetSortByEmail()
        {
            _users = _iUserService.SortByEmail().ToList();
            return Page();
        }

        public IActionResult OnGetSortByNameEmail()
        {
            _users = _iUserService.SortByEmailDescending().ToList();
            return Page();
        }

        public IActionResult OnGetClients()
        {
            _users = _iUserService.GetClients().ToList();
            return Page();
        }

        public IActionResult OnGetStaff()
        {
            _users = _iUserService.GetStaff().ToList();
            return Page();
        }
       
        public IActionResult OnPostEmailSearch()
        {
            _users = _iUserService.SearchUserByEmail(SearchString).ToList();
            return Page();
        }

        
    }
}

Program/Pages/Admin/ToolsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Admin
{   // Made by Christian
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "staff")]
    public class ToolsPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Program/Pages/Admin/UpdateUser.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace CTTSite.Pages.Admin
{
	// Made by Christian
	[Authorize(Roles = "admin")]
	public class UpdateUserModel : PageModel
    {
        private IUserService _userService;

        public UpdateUserModel(IUserService userService)
        {
            _userService = userService;
        }
        private PasswordHasher<string> passwordHasher;

        public string Message { get; set; }
        

        public Models.User user { get; set; }

        [BindProperty]
        public string Email { get; set; }
		
        [BindProperty, DataType(DataType.Password)]
		public string Password { get; set; }

        public IActionResult OnGet(int id)
        {
            user = _userService.GetUserByID(id);
            return Page();
        }

        public IActionResult OnPost(int id) 
        {
            user = _userService.GetUserByID(id);

            if (!ModelState.IsValid)
            {
                Message = "Something Went Wrong. Please Try Again";
                return RedirectToPage("UpdateUser", new {id = user.Id});
			}

            passwordHasher = new PasswordHasher<string>();
			user = _userService.GetUserByID(id);
			user.Id = user.Id;
            user.Email = Email;
			user.Password = passwordHasher.HashPassword(null, Password);
            user.Admin = user.Admin;
            user.Staff = user.Staff;

            
			_userService.UpdateUserAsync(user);
            return RedirectToPage("GetAllUsers");

        }
    }
}

Program/Pages/Admin/CreateStaffUser.cshtml
@page
@model CTTSite.Pages.Staff.Admin.CreateStaffUserModel
@{
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center">
<h1>Create a new Staff Member Login</h1>
<br />

<div class="row">
    <div class="container">
    <div class=" text-danger">
            @Model.Message
    </div>
    <div class="col-md-12">
            <br />
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Email" class="control-lable"></label>
                <input asp-for="@Model.Email" class="form-control" />
                <span asp-validation-for="@Model.newUser.Email" class="text-danger"></span>
            </div>
                <br />
            <div class="form-group">
                <p>A randomly generated password will be sent to the user which they are instructed to change when the log in</p>

            </div>
                <br />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-dark" />
                    <a asp-page="/Admin/ToolsPage" class="btn btn-outline-dark">Back</a>
            </div>
        </form>
    </div>
</div>
</div>
        </div>
            <div class="col-md-1"></div>
       
    </div>
</div>

Program/Pages/Admin/DeleteUser.cshtml
@page
@model CTTSite.Pages.Admin.DeleteUserModel
@{
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center">
<h1>Delete Confirmation></h1>
<div class="alert alert-danger">
	<h5>Are you sure you want to delete User - @Model.user.Email</h5>
	<form method="post">
		<button type="submit" class="btn btn-danger">Yes</button>
		<a class="btn btn-dark" asp-page="GetAllUsers">No</a>
	</form>
</div>
</div>
<div class="col-md-1"></div>
</div>
</div>

Program/Pages/Admin/GetAllUsers.cshtml
@page
@model CTTSite.Pages.Staff.Admin.GetAllUsersModel
@{
}

<div class="container-fluid">
	<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-10">

			<h1>Users</h1>

			<div class="row">
				<div class="col-7"><h5>Search Name</h5></div>	
				<div class="col-1"></div>
			</div>

			<div class="row">
				<div class="col-4">
					<form method="post" class="form-inline">
						<div class="input-group mb-3">
							<input asp-for="SearchString" class="form-control mr-1" placeholder="Enter User Email" />
							<input type="submit" asp-page-handler="EmailSearch" value="Search" class="btn btn-dark" />			
						</div>
					</form>
					<p>
						<a class="btn btn-dark" title="See Staff Users" asp-page-handler="Staff">See Staff Users</a>
						<a class="btn btn-dark" title="See Client Users" asp-page-handler="Clients">See Client Users</a>
						<a class="btn btn-dark" title="See All Users" asp-page-handler="All">See All</a>
					</p>
				</div>	
			</div>

			<table class="table table-bordered table-hover table-dark" width="80%">
				<colgroup>
					<col style="width : 5%">
					<col style="width : 77%">
					<col style="width : 9%">
		
				</colgroup>
				<thead>
					<tr class="btn-secondary active">
						<th>
							<div class="d-flex justify-content-between p-0">
								<div><h5>Id </h5></div>
								<div>
									<a data-toggle="tooltip" title="Sort By Id" asp-page-handler="SortById"><i class="fa fa-angle-up text-white"></i></a>
									<a data-toggle="tooltip" title="Sort By Id Descending" asp-page-handler="SortByIdDescending"><i class="fa fa-angle-down text-white"></i></a>
								</div>
							</div>
						</th>
						<th>
							<div class="d-flex justify-content-between p-0">
								<div>
									<h5>Name </h5>
								</div>
								<div>
									<a data-toggle="tooltip" title="Sort By Email" asp-page-handler="SortByEmail"><i class="fa fa-angle-up text-white"></i></a>
									<a data-toggle="tooltip" title="Sort By Email Descending" asp-page-handler="SortByNameEmail"><i class="fa fa-angle-down text-white"></i></a>
								</div>
							</div>

						</th>			
						<th>
							<h5>Action</h5>
						</th>
					</tr>
				</thead>
				<tbody>
					@if (Model._users != null)
					{
						foreach (Models.User user in Model._users)
						{
							<tr class="btn-secondary">
								<td class="text-white">
									@user.Id
								</td>
								<td class="text-white">
									@user.Email
								</td>										
								<td>
									<a class="btn btn-sm" type="button" title="Update" asp-page="UpdateUser" asp-route-id="@user.Id"><i class="fa fa-edit" style="color: #CCEAF6"></i></a>
									<a class="btn btn-sm " type="button" title="Delete" asp-page="DeleteUser" asp-route-id="@user.Id"><i class="fa fa-trash" style="color: #E0F6CC"></i></a>
								</td>
							</tr>
						}
					}
				</tbody>
			</table>

			<p>
				<a class="btn btn-dark" asp-page="/Staff/CreateClientUser"> Create Client User </a>
				<a class="btn btn-dark" asp-page="CreateStaffUser"> Create Staff User </a>
				<a asp-page="/Admin/ToolsPage" class="btn btn-outline-dark">Back</a>
			</p>

		
		</div>
		<div class="col-md-1"></div>
	</div>
</div>

Program/Pages/Admin/ToolsPage.cshtml
@page
@model CTTSite.Pages.Admin.ToolsPageModel
@{
}

<div class="container-fluid text-center text-dark">
    

<h1>Tools</h1>
    <br />

    <div class="row" style="margin-left: 5%; margin-right:5%">
    @if (HttpContext.User.Identity != null && HttpContext.User.IsInRole("admin") == true)
    {            

            <div class="col-3">
                <a class="btn btn-dark" asp-area="" asp-page="/Consultation/GetAllConsultaionsPage">Consultations</a>
                <br />
                <p>View the list of all future consultation bookings and create new timeslots for consultations.</p>
            </div>

            <div class="col-3">
                <a class="btn btn-dark" asp-area="" asp-page="/Store/Order/AllOrderPage">View all orders</a>
                <br />
                <p>View the list of all orders and see there status.</p>
            </div>

            <div class="col-3">
                <a class="btn btn-dark" asp-area="" asp-page="/Store/Product/AdminProductsPage">Edit Products</a>
                <br />
                <p>View the list of all products, see there status & edit them.</p>
            </div>

            <div class="col-3">
                <a class="btn btn-dark" asp-area="" asp-page="/Admin/GetAllUsers">See Users</a>
                <br />
                <p>View the list of all users, search users, edit and delete users and sort for staff and clients.</p>
            </div>

            <div class="col-3">
                <a class="btn btn-dark" asp-area="" asp-page="/Admin/CreateStaffUser">Create Staff User</a>
                <br />
                <p>Create new users with staff permissions.</p>
            </div>
    }
        @if (HttpContext.User.Identity != null && HttpContext.User.IsInRole("staff") == true)
        {
            <div class="col-3">
                <a class="btn btn-dark" asp-area="" asp-page="/Staff/CreateClientUser">Create Client User</a>
                <br />
                <p>Create new users with client permissions.</p>
            </div>
            <div class="col-3">
                <a class="btn btn-dark" asp-area="" asp-page="/TheRoomBooking/AllRoomBookingsPage">Therapy Room</a>
                <br />
                <p>See what times the room is booked, make new bookings and edit bookings.</p>
            </div>
        }
        
    </div>
</div>

Program/Pages/Admin/UpdateUser.cshtml
@page
@model CTTSite.Pages.Admin.UpdateUserModel
@{
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
	<h1 class="text-center">Update User: @Model.user.Email</h1>

	<h3 class="text-danger">
		@Model.Message
	</h3>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
	<form method="post">
		<div class="form-group">
			<label asp-for="@Model.user.Id" class="control-label"></label>
			<input asp-for="@Model.user.Id" class="form-control" readonly />
			<span asp-validation-for="@Model.user.Id" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="@Model.Email" class="control-label"></label>
			<input asp-for="@Model.Email" value="@Model.user.Email" class="form-control" />
			<span asp-validation-for="@Model.user.Email" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="@Model.Password" class="control-label"></label>
			<input asp-for="@Model.Password" class="form-control" />
			<span asp-validation-for="@Model.user.Password" class="text-danger"></span>
		</div>

		<p>
			<div class="form-group">
				<input type="submit" value="Update" class="btn btn-dark" />
				<a asp-page="GetAllUsers" class="btn btn-outline-dark">All Users</a>
			</div>
		</p>
	</form>
			</div>
		</div>
	</div>
	<p class="text-danger">
		Please be aware tgat if you change the password, the user will have to reset their password to login. 
		Also be aware that changing the email will change the username and may disconnect the user from some aspects of there account such as their saved forms.
		</p>
		<br />
	<p class="text-dark">
		If the details are not valid, this page will load again. If they are correct, you will be sent back to the All Users page.
	</p>
	</div>
	<div class="col-md-1"></div>
	</div>
	</div>