Program/Pages/Store/Cart/DeleteCartItemPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Cart
{
    // Made by Mads
    public class DeleteCartItemPageModel : PageModel
    {
        private readonly ICartItemService _cartItemService;

        [BindProperty]
        public CartItem CartItem { get; set; }

        public DeleteCartItemPageModel(ICartItemService cartItemService)
        {
            _cartItemService = cartItemService;
        }

        public async Task OnGetAsync(int ID)
        {
            CartItem = await _cartItemService.GetCartItemByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _cartItemService.RemoveFromCartByIDAsync(CartItem.ID);
            return RedirectToPage("SpecificUserCartPage");
        }
    }
}

Program/Pages/Store/Cart/SpecificUserCartPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Cart
{
    // Made by Mille & Mads
    public class SpecificUserCartPageModel : PageModel
    {
        private readonly ICartItemService _cartItemService;
        private readonly IUserService _userService;

        [BindProperty]
        public List<CartItem> CartItems { get; set; }
        public int CartItemsCount { get; set; }
        public decimal TotalPrice { get; set; }

        public SpecificUserCartPageModel(ICartItemService cartItemService, IUserService userService)
        {
            _cartItemService = cartItemService;
            _userService = userService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Models.User currentUser = _userService.GetUserByEmail(HttpContext.User.Identity.Name);
            CartItems = await _cartItemService.GetAllCartItemsByUserIDAsync(currentUser.Id);
            TotalPrice = await _cartItemService.GetTotalPriceOfCartByUserIDAsync(currentUser.Id);
            CartItemsCount = CartItems.Count;
            return Page();
        }
    }
}

Program/Pages/Store/Order/AllOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class AllOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;
        public List<Models.Order> Orders;

        [BindProperty]
        public string SearchString { get; set; }

        public AllOrderPageModel(IOrderService iOrderService)
        {
            _orderService = iOrderService;
        }

        public async Task<IActionResult> OnPostSearchOrderAsync()
        {
            Orders = await _orderService.GetOrdersByIDAsync(SearchString);
            return Page();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Orders = await _orderService.GetAllOrdersAsync();
            return Page();
        }

        public async Task<IActionResult> OnGetAllAsync()
        {
            Orders = await _orderService.GetAllOrdersAsync();
            return Page();
        }

        public async Task<IActionResult> OnGetUnShippedAsync()
        {
            Orders = await _orderService.GetAllUnShippedOrdersAsync();
            return Page();
        }
    }
}

Program/Pages/Store/Order/CancelOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    public class CancelOrderPageModel : PageModel
    {
        private readonly IOrderService _iOrderService;
        public Models.Order Order { get; set; }

        public CancelOrderPageModel(IOrderService iOrderService)
        {
            _iOrderService = iOrderService;
        }

        public async Task OnGetAsync(int ID)
        {
            Order = await _iOrderService.GetOrderByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync(int ID)
        {
            await _iOrderService.CancelOrderByIDAsync(ID);
            await _iOrderService.SubmitCancelOrderByEmailAsync(ID, HttpContext.User.Identity.Name);
            return RedirectToPage("SpecificUserOrderPage");
        }
    }
}

Program/Pages/Store/Order/DeleteOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    [Authorize(Roles = "admin")]
    public class DeleteOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;

        [BindProperty]
        public Models.Order Order { get; set; } 

        public DeleteOrderPageModel(IOrderService orderService)
        {
            _orderService = orderService;
        }


        public async Task OnGetAsync(int ID)
        {
            Order = await _orderService.GetOrderByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _orderService.DeleteOrderByOrderIDAsync(Order.ID);
            return RedirectToPage("/Store/Order/AllOrderPage");
        }
    }
}

Program/Pages/Store/Order/EditOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    [Authorize(Roles = "admin")]
    public class EditOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;

        [BindProperty]
        public Models.Order Order { get; set; }

        public EditOrderPageModel(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public async Task OnGetAsync(int ID)
        {
            Order = await _orderService.GetOrderByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            await _orderService.UpdateOrderAsync(Order);
            return RedirectToPage("/Store/Order/AllOrderPage");
        }
    }
}

Program/Pages/Store/Order/OrderConfirmationPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mille & Mads
    public class OrderConfirmationPageModel : PageModel
    {
        private readonly IOrderService _orderService;
        public int OrderID { get; set; }

        public OrderConfirmationPageModel(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public async Task OnGetAsync()
        {
            OrderID = await _orderService.GetLatestOrderFromUserAsync(User.Identity.Name);
        }
    }
}

Program/Pages/Store/Order/SpecificUserOldOrderPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    public class SpecificUserOldOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;

        [BindProperty]
        public Models.Order Order { get; set; }
        public decimal TotalPrice { get; set; }
        public List<CartItem> CartItems { get; set; } = new List<CartItem>();

        public SpecificUserOldOrderPageModel(IUserService userService, IOrderService orderService)
        {
            _userService = userService;
            _orderService = orderService;
        }


        public async Task<IActionResult> OnGetAsync(int ID)
        {
            Models.User CurrentUser = _userService.GetUserByEmail(HttpContext.User.Identity.Name);
            Order = await _orderService.GetOrderByIDAsync(ID);
            CartItems = await _orderService.GetOldOrderByOrderIDAsync(ID);
            TotalPrice = Order.TotalPrice;
            return Page();
        }
    }
}

Program/Pages/Store/Order/SpecificUserOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    public class SpecificUserOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;

        public List<Models.Order> Orders { get; set; }

        public SpecificUserOrderPageModel(IOrderService orderService, IUserService userService)
        {
            _orderService = orderService;
            _userService = userService;
        }

        public async Task OnGetAsync()
        {
            Models.User CurrentUser = _userService.GetUserByEmail(HttpContext.User.Identity.Name);
            Orders = await _orderService.GetOrdersByUserIDAsync(CurrentUser.Id);
        }
    }
}

Program/Pages/Store/Product/AdminProductsPage.cshtml.cs
using CTTSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class AdminProductsPageModel : PageModel
    {
        private readonly IItemService _itemService;
        public List<Models.Item> Items;

        public AdminProductsPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task OnGetAsync()
        {
            Items = await _itemService.GetAllItemsAsync();
        }
    }
}

Program/Pages/Store/Product/AllProductsPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using CTTSite.Services.NormalService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    public class AllProductsPageModel : PageModel
    {
        private readonly IItemService _itemService;
        public List<Item> Items;
        
        public AllProductsPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task OnGetAsync()
        {
            Items = await _itemService.GetAllItemsAsync();
        }
    }
}

Program/Pages/Store/Product/CreateProductPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class CreateProductPageModel : PageModel
    {
        private readonly IItemService _itemService;

        [BindProperty]
        public Item Item { get; set; }

        public CreateProductPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _itemService.CreateItemAsync(Item);

            return RedirectToPage("AdminProductsPage");
        }
    }
}

Program/Pages/Store/Product/DeleteProductPage.cshtml.cs
using CTTSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class DeleteProductPageModel : PageModel
    {
        private readonly IItemService _itemService;

        [BindProperty]
        public Models.Item Item { get; set; }

        public DeleteProductPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task OnGetAsync(int ID)
        {
            Item = await _itemService.GetItemByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _itemService.DeleteItemByIDAsync(Item.ID);
            return RedirectToPage("AdminProductsPage");
        }
    }
}

Program/Pages/Store/Product/SpecificProductPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    public class SpecificProductPageModel : PageModel
    {
        private readonly IItemService _itemService;
        private readonly ICartItemService _cartItemService;
        private readonly IUserService _userService;

        [BindProperty]
        public Item Item { get; set; }

        public CartItem CartItem { get; set; } = new CartItem();

        public Models.User User { get; set; }
        public string Message { get; set; }
        public string MessageColor { get; set; }

        [BindProperty]
        public int Count { get; set; }

        public SpecificProductPageModel(IItemService itemService, ICartItemService cartItemService, IUserService userService)
        {
            _itemService = itemService;
            _cartItemService = cartItemService;
            _userService = userService;
        }

        public async Task OnGetAsync(int ID)
        {
            Item = await _itemService.GetItemByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync(int ID)
        {
            Item = await _itemService.GetItemByIDAsync(ID);
            User = _userService.GetUserByEmail(HttpContext.User.Identity.Name);

            if (Count > Item.Stock)
            {
                MessageColor = "red";
                Message = $"There are only {Item.Stock} left in stock";
                return Page();
            }

            if (Count <= 0)
            {
                MessageColor = "red";
                Message = "There must be a valid amount";
                return Page();
            }

            if (Count <= Item.Stock)
            {
                MessageColor = "green";
                Message = $"{Item.Name} has been add to your cart";
            }

            CartItem.ItemID = ID;
            CartItem.Quantity = Count;
            CartItem.UserID = User.Id;
            CartItem.Paid = false;

            await _cartItemService.AddToCartAsync(CartItem);
            return Page();
        }
    }
}

Program/Pages/Store/Shipping/CreateShippingPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Shipping
{
    // Made by Mille & Mads
    public class CreateShippingPageModel : PageModel
    {
        private readonly IShippingInfoService _shippingInfoService;
        private readonly IOrderService _orderService;
        private readonly IItemService _itemService;
        private readonly ICartItemService _cartItemService;
        private readonly IUserService _userService;

        [BindProperty]
        public ShippingInfo ShippingInfo { get; set; } = new ShippingInfo();

        [BindProperty]
        public Models.Order Order { get; set; } = new Models.Order();

        public List<CartItem> CartItems { get; set; } = new List<CartItem>();

        public CreateShippingPageModel(IShippingInfoService shippingInfoService, IOrderService orderService, IItemService itemService, ICartItemService cartItemService, IUserService userService)
        {
            _cartItemService = cartItemService;
            _shippingInfoService = shippingInfoService;
            _orderService = orderService;
            _itemService = itemService;
            _userService = userService;
        }

        public async Task OnGetAsync()
        {
            Models.User currentUser = _userService.GetUserByEmail(HttpContext.User.Identity.Name);
            CartItems = await _cartItemService.GetAllCartItemsByUserIDAsync(currentUser.Id);
        }


        public async Task<IActionResult> OnPostCreateOrderAsync()
        {
            Models.User currentUser = _userService.GetUserByEmail(HttpContext.User.Identity.Name);
            CartItems = await _cartItemService.GetAllCartItemsByUserIDAsync(currentUser.Id);
            ShippingInfo.UserID = currentUser.Id;
            ShippingInfo.SubmissionDate = DateTime.Now;
            Order.UserID = currentUser.Id;
            Order.Shipped = false;
            Order.Cancelled = false;
            Order.TotalPrice = await _cartItemService.GetTotalPriceOfCartByUserIDAsync(currentUser.Id);
            await _orderService.CreateOrderAsync(Order);
            ShippingInfo.OrderID = Order.ID;
            await _shippingInfoService.CreateShippingInfoAsync(ShippingInfo);
            if (CartItems != null)
            {
                foreach (CartItem cartItem in CartItems)
                {
                    await _itemService.UpdateItemQuantityByIDAsync(cartItem.ItemID, cartItem.Quantity);
                }
            }
            await _shippingInfoService.SubmitShippingInfoByEmailAsync(ShippingInfo, currentUser.Email);
            await _orderService.AddCartItemsToOrderAsync(currentUser.Id);
            await _cartItemService.ConvertBoolPaidByUserIDAsync(currentUser.Id);
            return RedirectToPage("/Store/Order/OrderConfirmationPage");
        }
    }
}

Program/Pages/Store/Shipping/CreateShippingPage.cshtml
@page
@model CTTSite.Pages.Store.Shipping.CreateShippingPageModel
@{
}

<div class="container-fluid text-center">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <h1 class="text-center"><b>Shipping Information</b></h1>
                </div>
                <div class="col-md-3"></div>
            </div>
            <br />
        </div>
        <form method="post">
            <div class="form-row">
                <div class="row">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="@Model.ShippingInfo.FirstName" class="control-label">First Name</label>
                            <input asp-for="@Model.ShippingInfo.FirstName" class="form-control" />
                            <span asp-validation-for="@Model.ShippingInfo.FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ShippingInfo.LastName" class="control-label">Last Name</label>
                            <input asp-for="@Model.ShippingInfo.LastName" class="form-control" />
                            <span asp-validation-for="@Model.ShippingInfo.LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ShippingInfo.PhoneNumber" class="control-label">Phone number</label>
                            <input asp-for="@Model.ShippingInfo.PhoneNumber" class="form-control" />
                            <span asp-validation-for="@Model.ShippingInfo.PhoneNumber" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ShippingInfo.Address" class="control-label">Address</label>
                            <input asp-for="@Model.ShippingInfo.Address" class="form-control" />
                            <span asp-validation-for="@Model.ShippingInfo.Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ShippingInfo.County" class="control-label">County</label>
                            <input asp-for="@Model.ShippingInfo.County" class="form-control" />
                            <span asp-validation-for="@Model.ShippingInfo.County" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ShippingInfo.City" class="control-label">City</label>
                            <input asp-for="@Model.ShippingInfo.City" class="form-control" />
                            <span asp-validation-for="@Model.ShippingInfo.City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.ShippingInfo.PostCode" class="control-label">PostCode</label>
                            <input asp-for="@Model.ShippingInfo.PostCode" class="form-control" />
                            <span asp-validation-for="@Model.ShippingInfo.PostCode" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <br />
                            <input type="submit" value="Continue" class="btn btn-dark" asp-page-handler="CreateOrder" />
                            <a asp-page="/Store/Cart/SpecificUserCartPage" class="btn btn-outline-dark">Back to Cart</a>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-1"></div>
</div>

Program/Pages/Store/Shipping/EditShippingPage.cshtml
@page "{id:int}"
@model CTTSite.Pages.Store.Shipping.EditShippingPageModel
@{
}
<div class="container-fluid text-center">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4 text-center">
            <form method="post">                
                <div class="form-row">               
                    <h1 class="text-center"><b>Edit Shipping Information</b></h1>
                    <br />
                    <div class="form-group" hidden>
                        <label asp-for="@Model.ShippingInfo.ID" class="control-lable"></label>
                        <input asp-for="@Model.ShippingInfo.ID" type="hidden" class="form-control" />
                    </div>
                    <div class="form-group" hidden>
                          <label asp-for="@Model.ShippingInfo.UserID" class="control-lable"></label>
                          <input asp-for="@Model.ShippingInfo.UserID" type="hidden" class="form-control" />
                    </div>
                    <div class="form-group" hidden>
                        <label asp-for="@Model.ShippingInfo.OrderID" class="control-lable"></label>
                        <input asp-for="@Model.ShippingInfo.OrderID" type="hidden" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ShippingInfo.FirstName" class="control-lable">First Name</label>
                        <input asp-for="@Model.ShippingInfo.FirstName" class="form-control" />
                        <span asp-validation-for="@Model.ShippingInfo.FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ShippingInfo.LastName" class="control-lable">Last Name</label>
                        <input asp-for="@Model.ShippingInfo.LastName" class="form-control" />
                        <span asp-validation-for="@Model.ShippingInfo.LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ShippingInfo.Address" class="control-lable">Address</label>
                        <input asp-for="@Model.ShippingInfo.Address" class="form-control" />
                        <span asp-validation-for="@Model.ShippingInfo.Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ShippingInfo.City" class="control-lable">City</label>
                        <input asp-for="@Model.ShippingInfo.City" class="form-control" />
                        <span asp-validation-for="@Model.ShippingInfo.City" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ShippingInfo.PostCode" class="control-lable">Post Code</label>
                        <input asp-for="@Model.ShippingInfo.PostCode" class="form-control" />
                        <span asp-validation-for="@Model.ShippingInfo.PostCode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ShippingInfo.County" class="control-lable">County</label>
                        <input asp-for="@Model.ShippingInfo.County" class="form-control" />
                        <span asp-validation-for="@Model.ShippingInfo.County" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ShippingInfo.PhoneNumber" class="control-lable">Phone Number</label>
                        <input asp-for="@Model.ShippingInfo.PhoneNumber" class="form-control" />
                        <span asp-validation-for="@Model.ShippingInfo.PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="@Model.ShippingInfo.SubmissionDate" class="control-lable">Subminsion Date</label>
                        <input asp-for="@Model.ShippingInfo.SubmissionDate" class="form-control" readonly="@(true)"  />
                    </div>

                    <br />
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-dark" />
                        <a asp-page="/Store/Order/AllOrderPage" class="btn btn-outline-dark">Back</a>
                    </div>              
                </div>       
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

Program/Pages/Store/Shipping/SpecificShippingPage.cshtml
@page "{id:int}"
@model CTTSite.Pages.Store.Shipping.SpecificShippingPageModel
@{
}

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Specific Shipping Page</title>
</head>
<body class="text-center" style="background-color:#f6d8cc;">
    @if (Model.ShippingInfo != null)
    {
        <div>
            <h1>@Model.ShippingInfo.FirstName Shipping info</h1>
            <p>Shipping ID: @Model.ShippingInfo.ID</p>
            <p>User ID: @Model.ShippingInfo.UserID</p>
            <p>Order ID: @Model.ShippingInfo.OrderID</p>
            <p>Address: @Model.ShippingInfo.Address</p>
            <p>City: @Model.ShippingInfo.City</p>
            <p>PostCode: @Model.ShippingInfo.PostCode</p>
            <p>County: @Model.ShippingInfo.County</p>
            <p>Phone Number: @Model.ShippingInfo.PhoneNumber</p>
            <p>First Name: @Model.ShippingInfo.FirstName</p>
            <p>Last Name: @Model.ShippingInfo.LastName</p>
            <p>Submission Date: @Model.ShippingInfo.SubmissionDate</p>
        </div>
        <a class="btn btn-dark" type="button" asp-page="/Store/Shipping/EditShippingPage" asp-route-id="@Model.ShippingInfo.OrderID">Update</a>
            <a asp-page="/Store/Order/AllOrderPage" class="btn btn-outline-dark">Back</a>
    }
</body>