Program/Pages/Store/Cart/DeleteCartItemPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Cart
{
    // Made by Mads
    public class DeleteCartItemPageModel : PageModel
    {
        private readonly ICartItemService _cartItemService;

        [BindProperty]
        public CartItem CartItem { get; set; }

        public DeleteCartItemPageModel(ICartItemService cartItemService)
        {
            _cartItemService = cartItemService;
        }

        public async Task OnGetAsync(int ID)
        {
            CartItem = await _cartItemService.GetCartItemByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _cartItemService.RemoveFromCartByIDAsync(CartItem.ID);
            return RedirectToPage("SpecificUserCartPage");
        }
    }
}

Program/Pages/Store/Cart/SpecificUserCartPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Cart
{
    // Made by Mille & Mads
    public class SpecificUserCartPageModel : PageModel
    {
        private readonly ICartItemService _cartItemService;
        private readonly IUserService _userService;

        [BindProperty]
        public List<CartItem> CartItems { get; set; }
        public int CartItemsCount { get; set; }
        public decimal TotalPrice { get; set; }

        public SpecificUserCartPageModel(ICartItemService cartItemService, IUserService userService)
        {
            _cartItemService = cartItemService;
            _userService = userService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Models.User currentUser = _userService.GetUserByEmail(HttpContext.User.Identity.Name);
            CartItems = await _cartItemService.GetAllCartItemsByUserIDAsync(currentUser.Id);
            TotalPrice = await _cartItemService.GetTotalPriceOfCartByUserIDAsync(currentUser.Id);
            CartItemsCount = CartItems.Count;
            return Page();
        }
    }
}

Program/Pages/Store/Order/AllOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class AllOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;
        public List<Models.Order> Orders;

        [BindProperty]
        public string SearchString { get; set; }

        public AllOrderPageModel(IOrderService iOrderService)
        {
            _orderService = iOrderService;
        }

        public async Task<IActionResult> OnPostSearchOrderAsync()
        {
            Orders = await _orderService.GetOrdersByIDAsync(SearchString);
            return Page();
        }

        public async Task<IActionResult> OnGetAsync()
        {
            Orders = await _orderService.GetAllOrdersAsync();
            return Page();
        }

        public async Task<IActionResult> OnGetAllAsync()
        {
            Orders = await _orderService.GetAllOrdersAsync();
            return Page();
        }

        public async Task<IActionResult> OnGetUnShippedAsync()
        {
            Orders = await _orderService.GetAllUnShippedOrdersAsync();
            return Page();
        }
    }
}

Program/Pages/Store/Order/CancelOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    public class CancelOrderPageModel : PageModel
    {
        private readonly IOrderService _iOrderService;
        public Models.Order Order { get; set; }

        public CancelOrderPageModel(IOrderService iOrderService)
        {
            _iOrderService = iOrderService;
        }

        public async Task OnGetAsync(int ID)
        {
            Order = await _iOrderService.GetOrderByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync(int ID)
        {
            await _iOrderService.CancelOrderByIDAsync(ID);
            await _iOrderService.SubmitCancelOrderByEmailAsync(ID, HttpContext.User.Identity.Name);
            return RedirectToPage("SpecificUserOrderPage");
        }
    }
}

Program/Pages/Store/Order/DeleteOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    [Authorize(Roles = "admin")]
    public class DeleteOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;

        [BindProperty]
        public Models.Order Order { get; set; } 

        public DeleteOrderPageModel(IOrderService orderService)
        {
            _orderService = orderService;
        }


        public async Task OnGetAsync(int ID)
        {
            Order = await _orderService.GetOrderByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _orderService.DeleteOrderByOrderIDAsync(Order.ID);
            return RedirectToPage("/Store/Order/AllOrderPage");
        }
    }
}

Program/Pages/Store/Order/EditOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    [Authorize(Roles = "admin")]
    public class EditOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;

        [BindProperty]
        public Models.Order Order { get; set; }

        public EditOrderPageModel(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public async Task OnGetAsync(int ID)
        {
            Order = await _orderService.GetOrderByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            await _orderService.UpdateOrderAsync(Order);
            return RedirectToPage("/Store/Order/AllOrderPage");
        }
    }
}

Program/Pages/Store/Order/OrderConfirmationPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mille & Mads
    public class OrderConfirmationPageModel : PageModel
    {
        private readonly IOrderService _orderService;
        public int OrderID { get; set; }

        public OrderConfirmationPageModel(IOrderService orderService)
        {
            _orderService = orderService;
        }

        public async Task OnGetAsync()
        {
            OrderID = await _orderService.GetLatestOrderFromUserAsync(User.Identity.Name);
        }
    }
}

Program/Pages/Store/Order/SpecificUserOldOrderPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    public class SpecificUserOldOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;

        [BindProperty]
        public Models.Order Order { get; set; }
        public decimal TotalPrice { get; set; }
        public List<CartItem> CartItems { get; set; } = new List<CartItem>();

        public SpecificUserOldOrderPageModel(IUserService userService, IOrderService orderService)
        {
            _userService = userService;
            _orderService = orderService;
        }


        public async Task<IActionResult> OnGetAsync(int ID)
        {
            Models.User CurrentUser = _userService.GetUserByEmail(HttpContext.User.Identity.Name);
            Order = await _orderService.GetOrderByIDAsync(ID);
            CartItems = await _orderService.GetOldOrderByOrderIDAsync(ID);
            TotalPrice = Order.TotalPrice;
            return Page();
        }
    }
}

Program/Pages/Store/Order/SpecificUserOrderPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Order
{
    // Made by Mads
    public class SpecificUserOrderPageModel : PageModel
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;

        public List<Models.Order> Orders { get; set; }

        public SpecificUserOrderPageModel(IOrderService orderService, IUserService userService)
        {
            _orderService = orderService;
            _userService = userService;
        }

        public async Task OnGetAsync()
        {
            Models.User CurrentUser = _userService.GetUserByEmail(HttpContext.User.Identity.Name);
            Orders = await _orderService.GetOrdersByUserIDAsync(CurrentUser.Id);
        }
    }
}

Program/Pages/Store/Product/AdminProductsPage.cshtml.cs
using CTTSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class AdminProductsPageModel : PageModel
    {
        private readonly IItemService _itemService;
        public List<Models.Item> Items;

        public AdminProductsPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task OnGetAsync()
        {
            Items = await _itemService.GetAllItemsAsync();
        }
    }
}

Program/Pages/Store/Product/AllProductsPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using CTTSite.Services.NormalService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    public class AllProductsPageModel : PageModel
    {
        private readonly IItemService _itemService;
        public List<Item> Items;
        
        public AllProductsPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task OnGetAsync()
        {
            Items = await _itemService.GetAllItemsAsync();
        }
    }
}

Program/Pages/Store/Product/CreateProductPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class CreateProductPageModel : PageModel
    {
        private readonly IItemService _itemService;

        [BindProperty]
        public Item Item { get; set; }

        public CreateProductPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _itemService.CreateItemAsync(Item);

            return RedirectToPage("AdminProductsPage");
        }
    }
}

Program/Pages/Store/Product/DeleteProductPage.cshtml.cs
using CTTSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class DeleteProductPageModel : PageModel
    {
        private readonly IItemService _itemService;

        [BindProperty]
        public Models.Item Item { get; set; }

        public DeleteProductPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task OnGetAsync(int ID)
        {
            Item = await _itemService.GetItemByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _itemService.DeleteItemByIDAsync(Item.ID);
            return RedirectToPage("AdminProductsPage");
        }
    }
}

Program/Pages/Store/Product/SpecificProductPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    public class SpecificProductPageModel : PageModel
    {
        private readonly IItemService _itemService;
        private readonly ICartItemService _cartItemService;
        private readonly IUserService _userService;

        [BindProperty]
        public Item Item { get; set; }

        public CartItem CartItem { get; set; } = new CartItem();

        public Models.User User { get; set; }
        public string Message { get; set; }
        public string MessageColor { get; set; }

        [BindProperty]
        public int Count { get; set; }

        public SpecificProductPageModel(IItemService itemService, ICartItemService cartItemService, IUserService userService)
        {
            _itemService = itemService;
            _cartItemService = cartItemService;
            _userService = userService;
        }

        public async Task OnGetAsync(int ID)
        {
            Item = await _itemService.GetItemByIDAsync(ID);
        }

        public async Task<IActionResult> OnPostAsync(int ID)
        {
            Item = await _itemService.GetItemByIDAsync(ID);
            User = _userService.GetUserByEmail(HttpContext.User.Identity.Name);

            if (Count > Item.Stock)
            {
                MessageColor = "red";
                Message = $"There are only {Item.Stock} left in stock";
                return Page();
            }

            if (Count <= 0)
            {
                MessageColor = "red";
                Message = "There must be a valid amount";
                return Page();
            }

            if (Count <= Item.Stock)
            {
                MessageColor = "green";
                Message = $"{Item.Name} has been add to your cart";
            }

            CartItem.ItemID = ID;
            CartItem.Quantity = Count;
            CartItem.UserID = User.Id;
            CartItem.Paid = false;

            await _cartItemService.AddToCartAsync(CartItem);
            return Page();
        }
    }
}

Program/Pages/Store/Product/UpdateProductPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mille & Mads
    [Authorize(Roles = "admin")]
    public class UpdateProductPageModel : PageModel
    {
        private readonly IItemService _itemService;

        [BindProperty]
        public Item Item { get; set; }

        public UpdateProductPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task<IActionResult> OnGetAsync(int ID)
        {
            Item = await _itemService.GetItemByIDAsync(ID);
            if (Item == null)
            {
                return RedirectToPage("AdminProductsPage");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            await _itemService.UpdateItemAsync(Item);
            return RedirectToPage("AdminProductsPage");
        }
    }
}

Program/Pages/Store/Product/UpdateStockOnProductPage.cshtml.cs
using CTTSite.Models;
using CTTSite.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace CTTSite.Pages.Store.Product
{
    // Made by Mads
    [Authorize(Roles = "admin")]
    public class UpdateStockOnProductPageModel : PageModel
    {
        private readonly IItemService _itemService;

        [BindProperty]
        public Item Item { get; set; }
        [BindProperty]
        public int count { get; set; }

        public UpdateStockOnProductPageModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public async Task<IActionResult> OnGetAsync(int ID)
        {
            Item = await _itemService.GetItemByIDAsync(ID);
            if (Item == null)
            {
                return RedirectToPage("AdminProductsPage");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _itemService.UpdateItemStockAsync(Item.ID, count);
            return RedirectToPage("AdminProductsPage");
        }
    }
}

Program/Pages/Store/Order/AllOrderPage.cshtml
@page
@model CTTSite.Pages.Store.Order.AllOrderPageModel
@{
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center">
            <div class="mb-3">
                <div class="row">
                    <div class="col-3">
                        <form method="post" class="form-inline">
                            <div class="input-group mb-3">
                                <input asp-for="SearchString" class="form-control mr-1" placeholder="Enter Order ID" />
                                <input type="submit" asp-page-handler="SearchOrder" value="Search" class="btn btn-dark" />
                            </div>
                        </form>
                        <p>
                            <a class="btn btn-dark" title="See All Orders" asp-page-handler="All">See All Orders</a>
                            <a class="btn btn-dark" title="See All Unshipped Orders" asp-page-handler="UnShipped">See All Unshipped Orders</a>
                        </p>
                    </div>
                </div>
            </div>
            <table class="table table-bordered table-hover table-dark" width="80%">
                <thead>
                    <tr class="btn-secondary active">
                        <th>Order Number</th>
                        <th>Order Shipped</th>
                        <th>Order Cancelled</th>
                        <th>Total Price</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (@Model.Orders != null)
                    {
                        foreach (Models.Order order in Model.Orders)
                        {
                            <tr class="btn-secondary">
                                <td>
                                    @order.ID
                                </td>
                                <td>
                                    <span class="@(order.Shipped ? "true-value" : "false-value")">
                                        @if (order.Shipped)
                                        {
                                            <i class="fa fa-check"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-times"></i>
                                        }
                                    </span>
                                </td>
                                <td>
                                    <span class="@(order.Cancelled ? "false-value"  : "true-value")">
                                        @if (order.Cancelled)
                                        {
                                            <i class="fa fa-check"></i>
                                        }
                                        else
                                        {
                                            <i class="fa fa-times"></i>
                                        }
                                    </span>
                                </td>
                                <td>
                                    £@order.TotalPrice
                                </td>
                                <td>
                                    <a class="btn btn-danger" type="button" asp-page="DeleteOrderPage" asp-route-id="@order.ID"><i class="fa fa-trash"></i></a>
                                    <a class="btn btn-secondary" type="button" asp-page="EditOrderPage" asp-route-id="@order.ID"><i class="fa fa-pencil-square-o"></i></a>
                                    <a class="btn btn-secondary" type="button" asp-page="/Store/Shipping/SpecificShippingPage" asp-route-id="@order.ID"><i class="fa fa-info-circle"></i></a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>

Program/Pages/Store/Order/CancelOrderPage.cshtml
@page "{id:int}"
@model CTTSite.Pages.Store.Order.CancelOrderPageModel
@{
}

<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-body">
                <p class="text-white"><b>Are you sure that you want to cancel your order: "@Model.Order.ID"</b></p>
            </div>
            <div class="modal-footer">
                <form method="post">
                    <button type="submit" class="btn btn-danger">Yes</button>
                    <a class="btn btn-secondary" asp-page="SpecificUserOrderPage">No</a>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#myModal").modal({ backdrop: "static" });
            $("#myModal").modal('show')
        })
    </script>
}

Program/Pages/Store/Order/DeleteOrderPage.cshtml
@page "{id:int}"
@model CTTSite.Pages.Store.Order.DeleteOrderPageModel
@{
}

<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content bg-dark">
            <div class="modal-body">
                <p class="text-white"><b>Are you sure that you want to delete this order: "@Model.Order.ID"</b></p>
            </div>
            <div class="modal-footer">
                <form method="post">
                    <button type="submit" class="btn btn-danger">Yes</button>
                    <a class="btn btn-secondary" asp-page="AllOrderPage">No</a>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#myModal").modal({ backdrop: "static" });
            $("#myModal").modal('show')
        })
    </script>
}

Program/Pages/Store/Order/EditOrderPage.cshtml
@page
@model CTTSite.Pages.Store.Order.EditOrderPageModel
@{
}


<div class="container-fluid text-center">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <h1 class="text-center"><b>Edit order</b></h1>
                </div>
                <div class="col-md-3"></div>
            </div>
            <br />
        </div>
        <form method="post">
            <div class="form-row">
                <div class="row"><
                    <div class="col-md-5"></div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label asp-for="@Model.Order.ID" class="control-lable">Order ID</label>
                            <input asp-for="@Model.Order.ID" class="form-control" readonly="@(true)" />
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Order.UserID" class="control-lable">User ID</label>
                            <input asp-for="@Model.Order.UserID" class="form-control" readonly="@(true)" />
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Order.TotalPrice" class="control-lable">Order's total price'</label>
                            <input asp-for="@Model.Order.TotalPrice" class="form-control" />
                            <span asp-validation-for="@Model.Order.TotalPrice" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Order.Shipped" class="control-label">Has the order been shipped</label>
                            <div>
                                <input asp-for="@Model.Order.Shipped" class="form-check-input" />
                                <span asp-validation-for="@Model.Order.Shipped" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="@Model.Order.Cancelled" class="control-label">Is the order canceled</label>
                            <div>
                                <input asp-for="@Model.Order.Cancelled" class="form-check-input" />
                                <span asp-validation-for="@Model.Order.Cancelled" class="text-danger"></span>
                            </div>
                        </div>
                        <br />
                        <form method="post" class="form-inline">
                            <div class="form-group">
                                <input type="submit" value="Update" class="btn btn-dark mr-2" />
                                <a asp-page="/Store/Order/AllOrderPage" class="btn btn-outline-dark">Back</a>
                            </div>
                        </form>
                        <div class="col-md-5"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-1"></div>
</div>

Program/Pages/Store/Order/OrderConfirmationPage.cshtml
@page 
@model CTTSite.Pages.Store.Order.OrderConfirmationPageModel
@{
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center">
            <div class="text-center">
                <h1>Thank you for your purchase!</h1><br />
                <h4>Your order number is: @Model.OrderID</h4><br /</h4>
                <h4>An email have been send to you with your shipping info and order number</h4><br /</h4>
                <h4>Please come again!</h4><br />
                <br />
                <a asp-page="/Store/Order/SpecificUserOldOrderPage" asp-route-id="@Model.OrderID" class="btn btn-dark">View your order</a>
                <a asp-page="/Index" class="btn btn-outline-dark">Back to Homepage</a>
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>

Program/Pages/Store/Order/SpecificUserOldOrderPage.cshtml
@page "{id:int}"
@model CTTSite.Pages.Store.Order.SpecificUserOldOrderPageModel
@{
}


<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center">
            <h1 class="text-center"><b>@Model.User.Identity.Name's Order: @Model.Order.ID</b></h1>
            <br />
            <table class="table table-bordered table-hover table-dark" width="80%">
                <thead>
                    <tr class="btn-secondary active">
                        <th>Product name</th>
                        <th>Product price</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @if (@Model.CartItems != null)
                    {
                        foreach (Models.CartItem cartItem in Model.CartItems)
                        {
                            <tr class="btn-secondary">
                                <td>
                                    @cartItem.Item.Name
                                </td>
                                <td>
                                    £@cartItem.Item.Price
                                </td>
                                <td>
                                    @cartItem.Quantity
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            <span id="total-price" class="btn btn-dark" disabled style="cursor: default;">Total price: £@Model.TotalPrice</span>
            <a class="btn btn-outline-dark" type="button" asp-page="SpecificUserOrderPage" asp-route-id="">Back to order history</a>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>

Program/Pages/Store/Order/SpecificUserOrderPage.cshtml
@page
@model CTTSite.Pages.Store.Order.SpecificUserOrderPageModel
@{
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10 text-center">
            <h1 class="text-center"><b>@Model.User.Identity.Name's Orders</b></h1>
            <br />
            <table class="table table-bordered table-hover table-dark" width="80%">
                <thead>
                    <tr class="btn-secondary active">
                        <th>Order Number</th>
                        <th>Total Price</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (@Model.Orders != null)
                    {
                        foreach (Models.Order order in Model.Orders)
                        {
                            <tr class="btn-secondary">
                                <td>
                                    @order.ID
                                </td>
                                <td>
                                    £@order.TotalPrice
                                </td>
                                <td class="d-flex justify-content-around align-items-center">
                                    <div class="d-flex align-items-center">
                                        @if (order.Shipped == true)
                                        {
                                            <p class="mr-2"><span class="badge badge-success">Order has benn shipped</span></p>
                                        }
                                        <a class="btn btn-secondary" type="button" asp-page="SpecificUserOldOrderPage" asp-route-id="@order.ID"><i class="fa fa-info-circle"></i></a>
                                        @if (order.Shipped != true)
                                        {
                                            <a class="btn btn-danger ml-2" type="button" asp-page="CancelOrderPage" asp-route-id="@order.ID"><i class="fa fa-trash"></i></a>
                                        }
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>