Program/Models/Forms/FormActivityList.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CTTSite.Models.Forms
{
    // Made by Christian
    public class FormActivityList 
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [Required]
        public string UserEmail { get; set; }

        public string Pleasure { get; set; }
        public string Exercise { get; set; }
        public string Achievement { get; set; }
        public string Social { get; set; }

        public FormActivityList()
        {
        }

        public FormActivityList(string user, string pleasure, string exercise, string achievement, string social)
        {
            UserEmail = user;
            Pleasure = pleasure;
            Exercise = exercise;
            Achievement = achievement;
            Social = social;
        }

        public override string ToString()
        {
            return $"Pleasure: {Pleasure}\nExercise: {Exercise}\nAchievement: {Achievement}\nSocial: {Social}";
        }
    }
}

Program/Pages/Forms/Create/CreateActivityDiaryPage.cshtml.cs
using CTTSite.Models.Forms;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

// Made by Christian

namespace CTTSite.Pages.Forms
{
    public class CreateActivityDiaryPageModel : PageModel
    {
        private IFormService _formService;

        [BindProperty]
        public FormActivityDiary formActivityDiary { get; set; } = new FormActivityDiary();

        public CreateActivityDiaryPageModel(IFormService formService)
        {
            _formService = formService;
        }
       
        

        public void OnGet()
        {
            
        }

        public IActionResult OnPostSaveForm() 
        { 
            _formService.CreateFormActivityDiary(formActivityDiary);
            return RedirectToPage("/Forms/FormsMenuPage");
        }
        

        
    }
}

Program/Pages/Forms/Create/CreateActivityListPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CTTSite.Models.Forms;

// Made by Christian

namespace CTTSite.Pages.Forms
{
    public class CreateActivityListPageModel : PageModel
    {
        private IFormService _formService;

        [BindProperty] 
        public FormActivityList formActivityList { get; set; } = new FormActivityList();

        public CreateActivityListPageModel(IFormService formService)
        {
            _formService = formService;
        }

        

        public void OnGet()
        {

        }

        public IActionResult OnPostSaveForm()
        {
            _formService.CreateFormActivityList(formActivityList);
            return RedirectToPage("/Forms/FormsMenuPage");
        }
    }
}

Program/Pages/Forms/Create/CreateActivitySchedulePage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CTTSite.Models.Forms;

// Made by Christian

namespace CTTSite.Pages.Forms
{
    public class CreateActivitySchedulePageModel : PageModel
    {
        private IFormService _formService;

        [BindProperty]
        public FormActivitySchedule formActivitySchedule { get; set; } = new FormActivitySchedule();

        public CreateActivitySchedulePageModel(IFormService formService)
        {
            _formService = formService;
        }

        

        public void OnGet()
        {

        }

        public IActionResult OnPostSaveForm()
        {
            _formService.CreateFormActivitySchedule(formActivitySchedule);
            return RedirectToPage("/Forms/FormsMenuPage");
        }
    }
}

Program/Pages/Forms/Create/CreateHotCrossBunPage.cshtml.cs
using CTTSite.Models.Forms;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

// Made by Christian

namespace CTTSite.Pages.Forms
{
    public class CreateHotCrossBunPageModel : PageModel
    {
        private IFormService _formService;

        [BindProperty]
        public FormHotCrossBun formHotCrossBun { get; set; } = new FormHotCrossBun();

        public CreateHotCrossBunPageModel(IFormService formService)
        {
            _formService = formService;
        }

        

        public void OnGet()
        {
            
        }

        public IActionResult OnPostSaveForm()
        {

            _formService.CreateFormHotCrossBun(formHotCrossBun);
            return RedirectToPage("/Forms/FormsMenuPage");
        }
    }
}

Program/Pages/Forms/Create/CreateSleepDiaryPage.cshtml.cs
using CTTSite.Models.Forms;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;

// Made by Christian

namespace CTTSite.Pages.Forms
{
    public class CreateSleepDiaryPageModel : PageModel
    {
        private IFormService _formService;

        [BindProperty]
        public FormSleepDiary formSleepDiary { get; set; } = new FormSleepDiary();

        public CreateSleepDiaryPageModel(IFormService formService)
        {
            _formService = formService;
        }

        public void OnGet()
        {

        }

        public IActionResult OnPostSaveForm()
        {
            _formService.CreateFormSleepDiary(formSleepDiary);
            return RedirectToPage("/Forms/FormsMenuPage");
        }

    }
}

Program/Pages/Forms/FormsMenuPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CTTSite.Models.Forms;
using CTTSite.Services.Interface;

// Made by Christian

namespace CTTSite.Pages.Forms
{
    public class FormsMenuPageModel : PageModel
    {
        private IFormService _formService;
        
        public FormActivityDiary formActivityDiary { get; set; }
        public FormActivityList formActivityList { get; set; }
        public FormActivitySchedule formActivitySchedule { get; set; }
        public FormHotCrossBun formHotCrossBun { get; set; }
        public FormSleepDiary formSleepDiary { get; set; }


        public FormsMenuPageModel(IFormService formService)
        {
            _formService = formService;

        }

        public void OnGet()
        {
            if (_formService.GetFormActivityDiaryByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formActivityDiary = _formService.GetFormActivityDiaryByUserEmail(HttpContext.User.Identity.Name);
            }
            else
            {
                formActivityDiary = null;
            }

            if (_formService.GetFormActivityListByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formActivityList = _formService.GetFormActivityListByUserEmail(HttpContext.User.Identity.Name);
            }
            else
            {
                formActivityList = null;
            }

            if (_formService.GetFormActivityScheduleByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formActivitySchedule = _formService.GetFormActivityScheduleByUserEmail(HttpContext.User.Identity.Name);
            }
            else
            {
                formActivitySchedule = null;
            }

            if (_formService.GetFormHotCrossBunByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formHotCrossBun = _formService.GetFormHotCrossBunByUserEmail(HttpContext.User.Identity.Name);
            }
            else
            {
                formHotCrossBun = null;
            }

            if (_formService.GetFormSleepDiaryByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formSleepDiary = _formService.GetFormSleepDiaryByUserEmail(HttpContext.User.Identity.Name);
            }
            else
            {
                formSleepDiary = null;
            }           
        }
    }
}

Program/Pages/Forms/Update/UpdateActivityDiaryPage.cshtml.cs
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using CTTSite.Models.Forms;
using Microsoft.Identity.Client;

// Made by Christian

namespace CTTSite.Pages.Forms
{
    public class UpdateActivityDiaryPageModel : PageModel
    {
        private IFormService _formService;
        public UpdateActivityDiaryPageModel(IFormService formService)
        {
            _formService = formService;
        }

        public string message { get; set; }

        [BindProperty]
        public FormActivityDiary formActivityDiary { get; set; } = new FormActivityDiary();

        public void OnGet(int id)
        {
            if (_formService.GetFormActivityDiaryByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formActivityDiary = _formService.GetFormActivityDiaryByUserEmail(HttpContext.User.Identity.Name);
            }
           else
            {
                RedirectToPage("/Forms/FormsMenuPage");
            }
        }

        public IActionResult OnPostSubmitForm() 
        { 
          bool filledOut = false;

            
            if ((formActivityDiary.Day7_2400 == "Please Fill Out") || (formActivityDiary.Day5_0700 == "Please Fill Out"))
            {
                filledOut = false;
                message = "Please fill out the form before submission or save the form for later";
                    
            }
            else
            {
                filledOut = true;
            }
            
            
            if (filledOut)
            {
               _formService.UpdateFormActivityDiary(formActivityDiary);
                

               _formService.SubmitFormActivityDiary(formActivityDiary, formActivityDiary.UserEmail);
               _formService.DeleteFormActivityDiary(formActivityDiary);
                return RedirectToPage("/Forms/FormsMenuPage");
            }
            else
            {
                _formService.UpdateFormActivityDiary(formActivityDiary);
                formActivityDiary = _formService.GetFormActivityDiaryById(formActivityDiary.ID);

                return Page();
            }
        }

        public IActionResult OnPostSaveForm() 
        {
            _formService.UpdateFormActivityDiary(formActivityDiary);
            return RedirectToPage("/Forms/FormsMenuPage");
        }
    }
}

Program/Pages/Forms/Update/UpdateActivityListPage.cshtml.cs
using CTTSite.Models.Forms;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Forms
{
    public class UpdateActivityListPageModel : PageModel
    {
        private IFormService _formService;

        [BindProperty]
        public FormActivityList formActivityList { get; set; }


        public string message { get; set; } 
        public UpdateActivityListPageModel(IFormService formService)
        {
            _formService = formService;
        }



        public void OnGet(int id)
        {
            if (_formService.GetFormActivityListByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formActivityList = _formService.GetFormActivityListByUserEmail(HttpContext.User.Identity.Name);
            }
            else
            {
                RedirectToPage("/Forms/FormsMenuPage");
            }
        }

        public IActionResult OnPostSubmitForm()
        {
            bool filledOut = false;


            if ((formActivityList.Exercise == "Please Fill Out") || (formActivityList.Pleasure == "Please Fill Out") || (formActivityList.Social == "Please Fill Out") || (formActivityList.Achievement == "Please Fill Out"))
            {
                filledOut = false;
                message = "Please fill out the form before submission or save the form for later";
                    
            }
            else
            {
                filledOut = true;
            }
            

            if (filledOut)
            {
                _formService.UpdateFormActivityList(formActivityList);
                

                _formService.SubmitFormActivityList(formActivityList, formActivityList.UserEmail);
                _formService.DeleteFormActivityList(formActivityList);
                return RedirectToPage("/Forms/FormsMenuPage");
            }
            else
            {
                _formService.UpdateFormActivityList(formActivityList);
                formActivityList = _formService.GetFormActivityListById(formActivityList.ID);

                return Page();
            }
        }

        public IActionResult OnPostSaveForm()
        {
            _formService.UpdateFormActivityList(formActivityList);
            return RedirectToPage("/Forms/FormsMenuPage");
        }
    }
}

Program/Pages/Forms/Update/UpdateActivitySchedulePage.cshtml.cs
using CTTSite.Models.Forms;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Forms
{
    public class UpdateActivitySchedulePageModel : PageModel
    {
        private IFormService _formService;

        [BindProperty]
        public FormActivitySchedule formActivitySchedule { get; set; }
        public string message { get; set; }

        public UpdateActivitySchedulePageModel(IFormService formService)
        {
            _formService = formService;
        }



        public void OnGet(int id)
        {
            if (_formService.GetFormActivityScheduleByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formActivitySchedule = _formService.GetFormActivityScheduleByUserEmail(HttpContext.User.Identity.Name);
            }
            else
            {
                RedirectToPage("/Forms/FormsMenuPage");
            }
        }

        public IActionResult OnPostSubmitForm()
        {
            bool filledOut = false;

            
                if ((formActivitySchedule.Score7 == "Please Fill Out") || (formActivitySchedule.Afternoon2 == "Please Fill Out"))
                {
                    filledOut = false;
                    message = "Please fill out the form before submission or save the form for later";
                }
                else
                {
                    filledOut = true;
                }
            

            if (filledOut)
            {
                _formService.UpdateFormActivitySchedule(formActivitySchedule);
                

                _formService.SubmitFormActivitySchedule(formActivitySchedule, formActivitySchedule.UserEmail);
                _formService.DeleteFormActivitySchedule(formActivitySchedule);
                return RedirectToPage("/Forms/FormsMenuPage");
            }
            else
            {
                _formService.UpdateFormActivitySchedule(formActivitySchedule);
                formActivitySchedule = _formService.GetFormActivityScheduleById(formActivitySchedule.ID);

                return Page();
            }
        }

        public IActionResult OnPostSaveForm()
        {
            _formService.UpdateFormActivitySchedule(formActivitySchedule);
            return RedirectToPage("/Forms/FormsMenuPage");
        }
    }
}

Program/Pages/Forms/Update/UpdateHotCrossBunPage.cshtml.cs
using CTTSite.Models.Forms;
using CTTSite.Services.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CTTSite.Pages.Forms
{
    public class UpdateHotCrossBunPageModel : PageModel
    {
        private IFormService _formService;

        [BindProperty]
        public FormHotCrossBun formHotCrossBun { get; set; }
        public string message { get; set; }

        public UpdateHotCrossBunPageModel(IFormService formService)
        {
            _formService = formService;
        }



        public void OnGet()
        {
            if (_formService.GetFormHotCrossBunByUserEmail(HttpContext.User.Identity.Name) != null)
            {
                formHotCrossBun = _formService.GetFormHotCrossBunByUserEmail(HttpContext.User.Identity.Name);
            }
            else
            {
                RedirectToPage("/Forms/FormsMenuPage");
            }
        }

        public IActionResult OnPostSubmitForm()
        {
            bool filledOut = false;

           
            
            if ((formHotCrossBun.Emotions == "Please Fill Out") || (formHotCrossBun.Thoughts == "Please Fill Out") || (formHotCrossBun.Physical == "Please Fill Out") || (formHotCrossBun.Behaviours == "Please Fill Out"))
            {
                filledOut = false;
                message = "Please fill out the form before submission or save the form for later";
            }
            else
            {
                filledOut = true;
            }
           

            if (filledOut)
            {
                _formService.UpdateFormHotCrossBun(formHotCrossBun);
                

                _formService.SubmitFormHotCrossBun(formHotCrossBun, formHotCrossBun.UserEmail);
                _formService.DeleteFormHotCrossBun(formHotCrossBun);
                return RedirectToPage("/Forms/FormsMenuPage");
            }
            else
            {
                _formService.UpdateFormHotCrossBun(formHotCrossBun);
                formHotCrossBun = _formService.GetFormHotCrossBunById(formHotCrossBun.ID);

                return Page();
            }
        }

        public IActionResult OnPostSaveForm()
        {
            _formService.UpdateFormHotCrossBun(formHotCrossBun);
            return RedirectToPage("/Forms/FormsMenuPage");
        }
    }
}

Program/Pages/Forms/Update/UpdateActivityListPage.cshtml
@page
@model CTTSite.Pages.Forms.UpdateActivityListPageModel
@{
}


<div class="col-md-12 text-center" style="margin-bottom:4%">
    <h1 class="text-center">Activity List</h1>
    <h3 class="text-danger text-center"> @Model.message</h3>
    <form method="post">
        <input type="submit" asp-page-handler="SaveForm" value="Save Form" class="btn btn-dark text-center" />
        
        <div class="container-fluid">
            <div class="row">
                 <div class="col-md-12">
                    <div class="form-group">
                         <label asp-for="@Model.formActivityList.UserEmail" class="control-lable"></label>
                         <input asp-for="@Model.formActivityList.UserEmail" class="form-control" value="@HttpContext.User.Identity.Name" readonly />
                     </div>
                 </div>
             </div>
             <br />
       


        <div class="row">
         <div class="col-md-6">
        <div class="form-group">
            <label asp-for="@Model.formActivityList.Pleasure " class="control-lable">Pleasure</label>
            <input asp-for="@Model.formActivityList.Pleasure" class="form-control" value="@Model.formActivityList.Pleasure" />
        </div>
        </div>

        <div class="col-md-6">
        <div class="form-group">
            <label asp-for="@Model.formActivityList.Exercise" class="control-lable">Exercise</label>
            <input asp-for="@Model.formActivityList.Exercise" class="form-control" value="@Model.formActivityList.Exercise" />
        </div>
        </div>
        </div>
            <br />

        <div class="row">
         <div class="col-md-6">
        <div class="form-group">
            <label asp-for="@Model.formActivityList.Achievement" class="control-lable">Achievement</label>
            <input asp-for="@Model.formActivityList.Achievement" class="form-control" value="@Model.formActivityList.Achievement" />
        </div>
        </div>

        
        <div class="col-md-6">
        <div class="form-group">
            <label asp-for="@Model.formActivityList.Social" class="control-lable">Social</label>
            <input asp-for="@Model.formActivityList.Social" class="form-control" value="@Model.formActivityList.Social" />
        </div>
                </div>
            </div>
        
        <br />

                <div class="row">

                    <div class="input-group col-md-12">
                        <div class="col-md-2"></div>
                        <div class="col-md-3 text-center">
                            <input type="submit" asp-page-handler="SaveForm" value="Save Form" class="btn btn-dark" />
                        </div>
                        <div class="col-md-2"></div>
                        <div class="col-md-3 text-center">
                            <input type="submit" asp-page-handler="SubmitForm" value="Submit Form" class="btn btn-danger" />
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                </div>
        </div>
        
        
    </form>
</div>

Program/Pages/Forms/Update/UpdateHotCrossBunPage.cshtml
@page
@model CTTSite.Pages.Forms.UpdateHotCrossBunPageModel
@{
}

<div class="col-md-12 text-center" style="margin-bottom:4%">
    <h1 class="text-center">Hot Cross Bun</h1>
    <h3 class="text-danger text-center"> @Model.message</h3>
    <form method="post">
        <input type="submit" asp-page-handler="SaveForm" value="Save Form" class="btn btn-dark text-center" />
    
        <div class="container-fluid">
            <div class="row">
        <div class="form-group">
            <label asp-for="@Model.formHotCrossBun.UserEmail" class="control-lable"></label>
            <input asp-for="@Model.formHotCrossBun.UserEmail" class="form-control" value="@HttpContext.User.Identity.Name" readonly />
        </div>
            </div>
        
            <br />

            <div class="row">
                <div class="col-md-6">
        <div class="form-group">
            <label asp-for="@Model.formHotCrossBun.Trigger " class="control-lable">Trigger</label>
            <input asp-for="@Model.formHotCrossBun.Trigger" class="form-control" value="@Model.formHotCrossBun.Trigger" />
        </div>
                </div>

                    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="@Model.formHotCrossBun.Thoughts" class="control-lable">Thoughts</label>
            <input asp-for="@Model.formHotCrossBun.Thoughts" class="form-control" value="@Model.formHotCrossBun.Thoughts" />
        </div>
                </div>
            </div>

                    <br />

                    <div class="row">
                        <div class="col-md-6">
        <div class="form-group">
            <label asp-for="@Model.formHotCrossBun.Emotions" class="control-lable">Emotions</label>
            <input asp-for="@Model.formHotCrossBun.Emotions" class="form-control" value="@Model.formHotCrossBun.Emotions" />
        </div>
                </div>

                                <div class="col-md-6">
        <div class="form-group">
            <label asp-for="@Model.formHotCrossBun.Behaviours" class="control-lable">Behaviours</label>
            <input asp-for="@Model.formHotCrossBun.Behaviours" class="form-control" value="@Model.formHotCrossBun.Behaviours" />
        </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="@Model.formHotCrossBun.Physical" class="control-lable">Physical</label>
                        <input asp-for="@Model.formHotCrossBun.Physical" class="form-control" value="@Model.formHotCrossBun.Physical" />
                    </div>
                </div>

                <div class="col-md-6"></div>
                </div>
           

            <br />
            <div class="row">
                <div class="input-group col-mb-12 text-center">
                    <p>Please only submit this form when all fields are filled out.</p>
                </div>
            </div>
            <div class="row">

                <div class="input-group col-md-12">
                    <div class="col-md-2"></div>
                    <div class="col-md-3 text-center">
                        <input type="submit" asp-page-handler="SaveForm" value="Save Form" class="btn btn-dark" />
                    </div>
                    <div class="col-md-2"></div>
                    <div class="col-md-3 text-center">
                        <input type="submit" asp-page-handler="SubmitForm" value="Submit Form" class="btn btn-danger" />
                    </div>
                    <div class="col-md-2"></div>
                </div>
            </div>

            </div>
        
    </form>
</div>